### PR TITLE
Render `NaN` as 'NaN', to make diffs visible in JSONified objects.

### PR DESCRIPTION
**Pull request by wolframkriesing**
I had a test failing and it showed me the same JSON.stringified object in expected as in actual. The difference was that one value was `NaN`. This will render `NaN` as the string "NaN", to make this difference visible.

### CODE REVIEW

**Comment by rluba** [comment]
Thank you, Wolfram.

What would you think of rendering it as `<NaN>`? It’s not valid JSON, but it lets you distinguish between `NaN` and the string `'NaN'`.

**Comment by wolframkriesing** [comment]
@rluba done. Good idea!

**Comment by rluba** [comment]
Thank you! 👌

**Comment by rluba** [comment]
Released as `v3.2.5`.

**Pull request merged**
